//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scale_Program
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public int Id { get; set; }
        public string NoParte { get; set; }
        public int ModProceso { get; set; }
        public int Proceso { get; set; }
        public int Paso { get; set; }
        public string Descripcion { get; set; }
        public double PesoMin { get; set; }
        public double PesoMax { get; set; }
        public int Cantidad { get; set; }
    }
}
