//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scale_Program
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo
    {
        public int Id { get; set; }
        public string NoModelo { get; set; }
        public int ModProceso { get; set; }
        public string Descripcion { get; set; }
        public bool UsaBascula1 { get; set; }
        public bool UsaPick2Light { get; set; }
        public bool UsaCamaraVision { get; set; }
        public string ProgramaVision { get; set; }
        public string Etapa1 { get; set; }
        public bool Activo { get; set; }
    }
}
